apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pod         
  template:
    metadata:
      labels:
        app: api-pod       
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: api-container
        image: wzzylima/tc-fiap:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: api-secret
        resources:
          requests:
            cpu: "250m"      # 100 millicores (0.1 CPU)
            memory: "348Mi"  # 256 Megabytes