apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/oficina_db"
  SPRING_DATASOURCE_USERNAME: "oficina"
  SPRING_DATASOURCE_PASSWORD: "fiapdesafiotc"
  JWT_SECRET: "chave-dev-minimo-256-bits-dev-dev-dev-dev-dev-dev-dev"