spring.application.name=tech-challenge-oficina-mecanica

spring.datasource.url=jdbc:postgresql://localhost:5432/tech_challenge_mecanica

# Database Credentials
spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver Class Name (Optional: Spring Boot detects this automatically from the URL)
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update