apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: prod
type: Opaque
stringData:
  POSTGRES_DB: oficina_db
  POSTGRES_USER: oficina
  POSTGRES_PASSWORD: change-me-in-production
